# Generated by Django 5.0.6 on 2026-02-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepfakeAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=50)),
                ("politician", models.CharField(max_length=100)),
                ("detected_at", models.DateTimeField()),
                ("severity", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="election_alerts",
                        to="videos.video",
                    ),
                ),
            ],
        ),
    ]
