# Generated by Django 5.0.6 on 2026-02-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=256, unique=True)),
                ("transaction_id", models.CharField(max_length=256)),
                ("timestamp", models.DateTimeField()),
                ("block_number", models.IntegerField()),
                ("verified", models.BooleanField(default=False)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockchain_record",
                        to="videos.video",
                    ),
                ),
            ],
        ),
    ]
