# Generated by Django 5.0.6 on 2026-02-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("voice_clone_score", models.FloatField()),
                ("breath_score", models.FloatField()),
                ("background_score", models.FloatField()),
                ("spectral_data", models.JSONField(default=dict)),
                ("details", models.JSONField(default=dict)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_analysis",
                        to="videos.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiometricAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("pulse_detected", models.BooleanField(default=False)),
                ("heart_rate", models.FloatField(blank=True, null=True)),
                ("micro_expressions", models.JSONField(default=dict)),
                ("blood_flow_data", models.JSONField(default=dict)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_analysis",
                        to="videos.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnsembleResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_score", models.FloatField()),
                ("verdict", models.CharField(max_length=10)),
                ("confidence", models.FloatField()),
                ("weights_used", models.JSONField(default=dict)),
                ("timeline_data", models.JSONField(default=list)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ensemble_result",
                        to="videos.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetadataAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("reencode_count", models.IntegerField(default=0)),
                (
                    "source_device",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("edit_history", models.JSONField(default=list)),
                ("compression_artifacts", models.JSONField(default=dict)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_analysis",
                        to="videos.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisualAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("face_swap_score", models.FloatField()),
                ("lighting_score", models.FloatField()),
                ("blink_score", models.FloatField()),
                ("lip_sync_score", models.FloatField()),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_analysis",
                        to="videos.video",
                    ),
                ),
            ],
        ),
    ]
