# Generated by Django 5.0.6 on 2026-02-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ensembleresult",
            name="details",
            field=models.JSONField(default=dict),
        ),
    ]
