# Generated by Django 5.0.6 on 2026-02-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_ensembleresult_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadataanalysis",
            name="details",
            field=models.JSONField(default=dict),
        ),
    ]
